import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import 'react-loading-skeleton/dist/skeleton.css'
import Providers from "@/utils/provider";

// const inter = Inter({ subsets: ["latin"] });
const lexend = Lexend({
  subsets: ['latin'],
  display: "swap",
  variable: '--font-lexend',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} bg-gray-300`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
